docs_dir: docs/
repo_name: 'CyVerse-learning-materials/cyverse_mooc'
repo_url: 'https://github.com/CyVerse-learning-materials/cyverse_mooc'

site_name: 'CyVerse Self-guided Course'
site_description: 'Introduction to CyVerse Self-guided Course'
site_author: 'CyVerse USA & CyVerse Austria'
site_url: https://CyVerse-learning-materials.io/cyverse_mooc/

edit_uri: edit/mkdocs-usa/docs

# Copyright
copyright: 'Copyright &copy; 2022 CyVerse USA'

# Navigation Page

nav:
  - 'Home': index.md 
  - 'Course Overview': step1.md
  - 'CyVerse Background': step2.md
  - 'Tour of Discovery Environment': step3.md  
  - 'Data Management I': step4.md
  - 'Data Management II': step5.md
  - 'Data Management III': step6.md
  - 'Analysis with the Discovery Environment': step7.md
  - 'Interactive Analyses': step8.md
  - 'Conclusion and Advanced Applications': final_step.md    
# JavaScript for Intercom Widget
extra_javascript:
  - javascripts/intercom-learning.js
  
# Set theme to `readthedocs`
# must also set Action to use `@nomaterial` branch instead of `@master` for material
theme:
  name: material
# setting features for the navigation tab
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - navigation.sections
    - navigation.expand
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: material/rocket
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

# Options
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/cyverse-learning-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject

#  analytics:
#    provider: google
#    property: 

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
